# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config| 
    config.omnibus.chef_version = :latest

    config.vm.define 'slave' do |c|
        c.vm.hostname = "slave"
        if ENV["VAGRANT_DEFAULT_PROVIDER"] == "lxc"
            c.vm.box = "ubuntu14.04-lxc-scalrpy"
            c.vm.box_url = "https://s3.amazonaws.com/scalr-labs/ubuntu1404-scalrpy.box"
        else
            c.vm.box = "ubuntu-14.04-x86_64"
            c.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
        end

        c.vm.network :forwarded_port, guest: 22, host: 2022

        c.vm.provision :shell, inline: "apt-get update"
        c.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = 'cookbooks'
            chef.json = {
            }
            chef.run_list = [
                "recipe[scalrpytests::default]",
                "recipe[scalrpytests::vagrant]",
                "recipe[scalrpytests::slave]"
            ]
        end
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id,
        "--memory", "1536",
        "--cpus", "1"
      ]
    end
end
